language: clojure
lein: lein
script:
  - lein all do clean, test
  - ! lein check 2>&1 | egrep "Reflection warning|Performance warning"
branches:
  only:
    - 3.x
    # 'master' is the new apache 5 client, and not passing yet
    # - master
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
